# Generated by Django 2.1.1 on 2018-09-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Administrator'), (2, 'Sales Agent'), (3, 'Business Partner'), (4, 'Introducer'), (5, 'BDM'), (6, 'Accountant'), (7, 'Acquisitions'), (8, 'Client')], primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField(choices=[(1, '15-25'), (2, '26-35'), (3, '36-50'), (4, '51+')])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile_number', models.PositiveIntegerField(unique=True)),
                ('office_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('post_code', models.PositiveSmallIntegerField()),
                ('purchasing_entity', models.CharField(max_length=100)),
                ('can_not_contact', models.BooleanField(default=True)),
                ('personal_income', models.PositiveIntegerField()),
                ('parters_income', models.PositiveIntegerField()),
                ('owned_properties', models.PositiveSmallIntegerField()),
                ('own_home', models.BooleanField(default=False)),
                ('gst_registered', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100)),
                ('abn', models.PositiveIntegerField()),
                ('australian_resident', models.BooleanField(default=True)),
                ('firb_required', models.BooleanField(default=False)),
                ('investment_needed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user_service.LeadSource')),
                ('role', models.ManyToManyField(related_name='users', to='user_service.Role')),
            ],
        ),
    ]
