# Generated by Django 2.1.1 on 2018-09-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parters_income',
            new_name='partners_income',
        ),
    ]
