# Generated by Django 2.1.1 on 2018-09-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_auto_20180913_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
