# Generated by Django 2.1.1 on 2018-09-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_auto_20180913_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
